"""empty message

Revision ID: 0611651198a7
Revises: 82f82174a0f2
Create Date: 2017-01-11 02:14:14.506690

"""

# revision identifiers, used by Alembic.
revision = '0611651198a7'
down_revision = '82f82174a0f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded__intv', sa.Column('image_name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded__intv', 'image_name')
    ### end Alembic commands ###
