"""empty message

Revision ID: 184782f13fe7
Revises: cf419a81bf28
Create Date: 2016-11-16 20:06:51.706700

"""

# revision identifiers, used by Alembic.
revision = '184782f13fe7'
down_revision = 'cf419a81bf28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mturk', sa.Column('w_access_token', sa.String(length=120), nullable=True))
    op.add_column('mturk', sa.Column('w_moves_id', sa.String(length=120), nullable=True))
    op.add_column('mturk', sa.Column('w_refresh_token', sa.String(length=120), nullable=True))
    op.drop_column('mturk', u'moves_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mturk', sa.Column(u'moves_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('mturk', 'w_refresh_token')
    op.drop_column('mturk', 'w_moves_id')
    op.drop_column('mturk', 'w_access_token')
    ### end Alembic commands ###
