"""empty message

Revision ID: 342917cebdcf
Revises: ab2584c8ddd6
Create Date: 2017-01-01 06:57:02.021401

"""

# revision identifiers, used by Alembic.
revision = '342917cebdcf'
down_revision = 'ab2584c8ddd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescuetime_user',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rt_access_token', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rt_access_token')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rescuetime_user')
    ### end Alembic commands ###
