"""empty message

Revision ID: 353af2180aae
Revises: 77393cbdd5ec
Create Date: 2016-12-29 17:30:20.331397

"""

# revision identifiers, used by Alembic.
revision = '353af2180aae'
down_revision = '77393cbdd5ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', u'no_of_condition')
    op.drop_column('experiment', u'ps_per_condition')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column(u'ps_per_condition', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column(u'no_of_condition', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
