"""empty message

Revision ID: 3dbec13f3b83
Revises: 0611651198a7
Create Date: 2017-01-31 18:10:30.441112

"""

# revision identifiers, used by Alembic.
revision = '3dbec13f3b83'
down_revision = '0611651198a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('experiment', sa.Column('start', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'start')
    op.drop_column('experiment', 'end')
    ### end Alembic commands ###
