"""empty message

Revision ID: 5d48c1d64db8
Revises: c6a2ba20827a
Create Date: 2016-12-12 01:15:40.480433

"""

# revision identifiers, used by Alembic.
revision = '5d48c1d64db8'
down_revision = 'c6a2ba20827a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textintv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imageintv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'intervention', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column(u'intervention', sa.Column('every', sa.String(length=30), nullable=True))
    op.add_column(u'intervention', sa.Column('group', sa.String(length=1500), nullable=True))
    op.add_column(u'intervention', sa.Column('repeat', sa.String(length=30), nullable=True))
    op.add_column(u'intervention', sa.Column('start', sa.String(length=120), nullable=True))
    op.add_column(u'intervention', sa.Column('when', sa.String(length=30), nullable=True))
    op.drop_column(u'intervention', u'date')
    op.drop_column(u'intervention', u'txt')
    op.drop_column(u'intervention', u'image_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'intervention', sa.Column(u'image_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'intervention', sa.Column(u'txt', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'intervention', sa.Column(u'date', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column(u'intervention', 'when')
    op.drop_column(u'intervention', 'start')
    op.drop_column(u'intervention', 'repeat')
    op.drop_column(u'intervention', 'group')
    op.drop_column(u'intervention', 'every')
    op.drop_column(u'intervention', 'created_at')
    op.drop_table('imageintv')
    op.drop_table('textintv')
    ### end Alembic commands ###
