"""empty message

Revision ID: 5ef466601281
Revises: 342917cebdcf
Create Date: 2017-01-01 08:07:18.278200

"""

# revision identifiers, used by Alembic.
revision = '5ef466601281'
down_revision = '342917cebdcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'rescuetime_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'rescuetime_user',
    sa.Column(u'email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column(u'rt_access_token', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'email', name=u'rescuetime_user_pkey')
    )
    ### end Alembic commands ###
