"""empty message

Revision ID: 651b64029e36
Revises: e48e7480b91e
Create Date: 2016-12-28 06:38:27.983011

"""

# revision identifiers, used by Alembic.
revision = '651b64029e36'
down_revision = 'e48e7480b91e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention', sa.Column('treatment', sa.String(length=2000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervention', 'treatment')
    ### end Alembic commands ###
