"""empty message

Revision ID: 6ccee4d2aecd
Revises: None
Create Date: 2017-02-01 00:02:08.291501

"""

# revision identifiers, used by Alembic.
revision = '6ccee4d2aecd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('no_of_condition', sa.Integer(), nullable=True),
    sa.Column('ps_per_condition', sa.Integer(), nullable=True),
    sa.Column('rescuetime', sa.Boolean(), nullable=True),
    sa.Column('aware', sa.Boolean(), nullable=True),
    sa.Column('geofence', sa.Boolean(), nullable=True),
    sa.Column('text', sa.Boolean(), nullable=True),
    sa.Column('image', sa.Boolean(), nullable=True),
    sa.Column('reminder', sa.Boolean(), nullable=True),
    sa.Column('actuators', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('picture', sa.String(length=120), nullable=True),
    sa.Column('google_credentials', sa.String(length=2500), nullable=True),
    sa.Column('is_location_active', sa.Boolean(), nullable=True),
    sa.Column('is_mood_active', sa.Boolean(), nullable=True),
    sa.Column('is_sn_active', sa.Boolean(), nullable=True),
    sa.Column('moves_id', sa.String(length=120), nullable=True),
    sa.Column('moves_access_token', sa.String(length=120), nullable=True),
    sa.Column('moves_refresh_token', sa.String(length=120), nullable=True),
    sa.Column('rescuetime_access_token', sa.String(length=120), nullable=True),
    sa.Column('rescuetime_refresh_token', sa.String(length=120), nullable=True),
    sa.Column('pam_access_token', sa.String(length=120), nullable=True),
    sa.Column('pam_refresh_token', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_credentials'),
    sa.UniqueConstraint('moves_access_token'),
    sa.UniqueConstraint('moves_id'),
    sa.UniqueConstraint('moves_refresh_token'),
    sa.UniqueConstraint('pam_access_token'),
    sa.UniqueConstraint('pam_refresh_token'),
    sa.UniqueConstraint('rescuetime_access_token'),
    sa.UniqueConstraint('rescuetime_refresh_token')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('experiment')
    ### end Alembic commands ###
