"""empty message

Revision ID: 77393cbdd5ec
Revises: 651b64029e36
Create Date: 2016-12-29 17:28:32.753453

"""

# revision identifiers, used by Alembic.
revision = '77393cbdd5ec'
down_revision = '651b64029e36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('no_of_condition', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('ps_per_condition', sa.Integer(), nullable=True))
    op.drop_column('intervention', u'condition')
    op.add_column('mobile_user', sa.Column('condition', sa.Integer(), nullable=True))
    op.add_column('mobile_user', sa.Column('gender', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobile_user', 'gender')
    op.drop_column('mobile_user', 'condition')
    op.add_column('intervention', sa.Column(u'condition', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('experiment', 'ps_per_condition')
    op.drop_column('experiment', 'no_of_condition')
    ### end Alembic commands ###
