"""empty message

Revision ID: 81733c1cd9a6
Revises: 45caecfa2ab0
Create Date: 2016-12-21 18:48:22.040910

"""

# revision identifiers, used by Alembic.
revision = '81733c1cd9a6'
down_revision = '45caecfa2ab0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention', sa.Column('condition', sa.Integer(), nullable=True))
    op.add_column('intervention', sa.Column('treatment', sa.String(length=250), nullable=True))
    op.drop_column('intervention', u'group')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention', sa.Column(u'group', sa.VARCHAR(length=1500), autoincrement=False, nullable=True))
    op.drop_column('intervention', 'treatment')
    op.drop_column('intervention', 'condition')
    ### end Alembic commands ###
