"""empty message

Revision ID: 82f82174a0f2
Revises: e067673e6700
Create Date: 2017-01-11 02:13:56.742846

"""

# revision identifiers, used by Alembic.
revision = '82f82174a0f2'
down_revision = 'e067673e6700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded__intv', u'image_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded__intv', sa.Column(u'image_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    ### end Alembic commands ###
