"""empty message

Revision ID: 8397a5865cbc
Revises: 5d48c1d64db8
Create Date: 2016-12-12 01:24:17.132890

"""

# revision identifiers, used by Alembic.
revision = '8397a5865cbc'
down_revision = '5d48c1d64db8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_user',
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobile_user')
    ### end Alembic commands ###
