"""empty message

Revision ID: 9be5d50fec0f
Revises: None
Create Date: 2017-02-08 14:26:59.159098

"""

# revision identifiers, used by Alembic.
revision = '9be5d50fec0f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mturk_fb_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('time_open', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mturk_fb_stats')
    ### end Alembic commands ###
