"""empty message

Revision ID: ab2584c8ddd6
Revises: 353af2180aae
Create Date: 2016-12-29 17:30:34.836815

"""

# revision identifiers, used by Alembic.
revision = 'ab2584c8ddd6'
down_revision = '353af2180aae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('no_of_condition', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('ps_per_condition', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'ps_per_condition')
    op.drop_column('experiment', 'no_of_condition')
    ### end Alembic commands ###
