"""empty message

Revision ID: b4796edef8f8
Revises: 8397a5865cbc
Create Date: 2016-12-12 01:32:38.490631

"""

# revision identifiers, used by Alembic.
revision = 'b4796edef8f8'
down_revision = '8397a5865cbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_user', sa.Column('code', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobile_user', 'code')
    ### end Alembic commands ###
