"""empty message

Revision ID: c6a2ba20827a
Revises: cede68f65fd5
Create Date: 2016-12-10 22:07:45.770504

"""

# revision identifiers, used by Alembic.
revision = 'c6a2ba20827a'
down_revision = 'cede68f65fd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('image', sa.Boolean(), nullable=True))
    op.add_column('experiment', sa.Column('text', sa.Boolean(), nullable=True))
    op.drop_column('experiment', u'text_image')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column(u'text_image', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('experiment', 'text')
    op.drop_column('experiment', 'image')
    ### end Alembic commands ###
