"""empty message

Revision ID: cede68f65fd5
Revises: 2c8d4f3b84f5
Create Date: 2016-12-08 04:34:56.404872

"""

# revision identifiers, used by Alembic.
revision = 'cede68f65fd5'
down_revision = '2c8d4f3b84f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('rescuetime', sa.Boolean(), nullable=True),
    sa.Column('aware', sa.Boolean(), nullable=True),
    sa.Column('geofence', sa.Boolean(), nullable=True),
    sa.Column('text_image', sa.Boolean(), nullable=True),
    sa.Column('reminder', sa.Boolean(), nullable=True),
    sa.Column('actuators', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.Column('txt', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervention')
    op.drop_table('experiment')
    ### end Alembic commands ###
