"""empty message

Revision ID: cf419a81bf28
Revises: faeb6f562001
Create Date: 2016-11-16 19:11:14.927722

"""

# revision identifiers, used by Alembic.
revision = 'cf419a81bf28'
down_revision = 'faeb6f562001'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mturk',
    sa.Column('worker_id', sa.String(length=120), nullable=False),
    sa.Column('moves_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('moves_id'),
    sa.UniqueConstraint('worker_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mturk')
    ### end Alembic commands ###
