"""empty message

Revision ID: d79594f77b6f
Revises: 81733c1cd9a6
Create Date: 2016-12-27 15:39:21.646369

"""

# revision identifiers, used by Alembic.
revision = 'd79594f77b6f'
down_revision = '81733c1cd9a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention', sa.Column('end', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervention', 'end')
    ### end Alembic commands ###
