"""empty message

Revision ID: e067673e6700
Revises: 5ef466601281
Create Date: 2017-01-11 00:02:35.443356

"""

# revision identifiers, used by Alembic.
revision = 'e067673e6700'
down_revision = '5ef466601281'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded__intv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('image_name', sa.String(length=30), nullable=True),
    sa.Column('text', sa.String(length=1500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'textintv')
    op.drop_table(u'imageintv')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'imageintv',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'image_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column(u'created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column(u'image_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'imageintv_pkey')
    )
    op.create_table(u'textintv',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'text', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column(u'created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'textintv_pkey')
    )
    op.drop_table('uploaded__intv')
    ### end Alembic commands ###
