"""empty message

Revision ID: e48e7480b91e
Revises: d79594f77b6f
Create Date: 2016-12-28 06:36:57.714408

"""

# revision identifiers, used by Alembic.
revision = 'e48e7480b91e'
down_revision = 'd79594f77b6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervention', u'treatment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention', sa.Column(u'treatment', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    ### end Alembic commands ###
